### ISSUE TITLE
Players of the game are visualized in the lobby

### ISSUE THREAD

**Issue by laendi22** [sopra-fs24-group-46/client#13]

**Comment by S3r4f1n** [comment]
Closed in : [562a901](https://github.com/sopra-fs24-group-46/client/commit/562a90174a062355b66575a587cf7ec23a7f7e26)

**Comment by RoVi80** [comment]
https://github.com/sopra-fs24-group-46/client/commit/8c747db20a684a4c770e55b87835b574ea0c6abe
