### ISSUE TITLE
End Leaderboard: The Points of the winners are visible

### ISSUE THREAD

**Issue by laendi22** [sopra-fs24-group-46/client#27]

**Comment by DarthDanAmesh** [comment]
closed via #[49f658a](https://github.com/sopra-fs24-group-46/client/commit/49f658adf769557c95c4947c36907dec0fdb351a)

**Comment by RoVi80** [comment]
https://github.com/sopra-fs24-group-46/client/commit/f058f039805ca0f30b60db1ff72e89c011f43fd8
