### ISSUE TITLE
Styling: As a User I want a visually pleasing experience when using the app. To not get distracted from the main functionalities.

### ISSUE THREAD

**Issue by laendi22** [sopra-fs24-group-46/client#66]
**Pages to Style:**
- [x] #86
- [x] #87
- [x] #88
- [x] #89
- [x] #90
- [x] #91
- [x] #92
- [x] #93
- [x] #94
- [x] #95
- [x] #96
- [x] #97
- [x] #98
- [x] #99
- [x] #100

**Comment by S3r4f1n** [comment]
Closing since all tasks are done
