### ISSUE TITLE
Refactor: Use api.get/post/put instead of fetch

### ISSUE THREAD

**Issue by S3r4f1n** [sopra-fs24-group-46/client#70]
Instead of using the the fetch syntax use the api. functionality. like in
Instead of
```java
const response = await fetch('${getDomain()}/game/${gameId}/getView');
```
use:
```java
const response = await api.get('/game/${gameId}/getView');
```
syntax for post:
```java
const response = await api.post('/game/${gameId}/start', requestBody);
```

Find usage of Fetch by serching whole client code.

This will allow for easy changes to headers e.g. adding tokens and game ids if needed.

**Comment by DarthDanAmesh** [comment]
closed with #[f173a49](https://github.com/sopra-fs24-group-46/client/commit/f173a498c4d8439ff4e06749e3f6dad6819a9d14)
