### ISSUE TITLE
Refactor: Page Routing. Rout Guards. Clean AppRouter File.

### ISSUE THREAD

**Issue by S3r4f1n** [sopra-fs24-group-46/client#74]
use a login gurad to:
- prevent users from seeing the profile page if not logged in. (from profile page to home page)
- redirect users to their profile page if they are logged in. (from homepage to profile page)

Use guard like in M1

**Comment by RoVi80** [comment]
https://github.com/sopra-fs24-group-46/client/commit/3e0bb4f8aa770497b8bb5c7bbbdf13ee2f0b376a
